version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: builder
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 80:3000
    command: npm run start:dev